// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// remove_stopword_cpp
std::vector<std::string> remove_stopword_cpp(std::list<std::vector<std::string>> x, std::vector<std::string> stwd);
RcppExport SEXP _text_analysis_remove_stopword_cpp(SEXP xSEXP, SEXP stwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list<std::vector<std::string>> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type stwd(stwdSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_stopword_cpp(x, stwd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_text_analysis_remove_stopword_cpp", (DL_FUNC) &_text_analysis_remove_stopword_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_text_analysis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
