# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

remove_stopword_cpp <- function(x, stwd) {
    .Call(`_text_analysis_remove_stopword_cpp`, x, stwd)
}

